"""update of vote

Revision ID: 4fa58bf352fd
Revises: 35392c97e431
Create Date: 2024-10-02 16:45:15.986861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fa58bf352fd'
down_revision: Union[str, None] = '35392c97e431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vote_match_id'), 'vote', ['match_id'], unique=False)
    op.create_index(op.f('ix_vote_user_id'), 'vote', ['user_id'], unique=False)
    op.drop_column('vote', 'sd_time')
    op.drop_column('vote', 'de_time')
    op.drop_column('vote', 'bv_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('bv_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('vote', sa.Column('de_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('vote', sa.Column('sd_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vote_user_id'), table_name='vote')
    op.drop_index(op.f('ix_vote_match_id'), table_name='vote')
    # ### end Alembic commands ###
