"""fixing barrier record

Revision ID: 35f7f7311190
Revises: 85c0315b1d61
Create Date: 2024-10-24 02:22:10.082298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35f7f7311190'
down_revision: Union[str, None] = '85c0315b1d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barrierrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_counter', sa.Integer(), nullable=False),
    sa.Column('simple_domain_counter', sa.Integer(), nullable=False),
    sa.Column('binding_vow_counter', sa.Integer(), nullable=False),
    sa.Column('barrier_tech_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barrier_tech_id'], ['barriertech.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('barrierdetail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barrierdetail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain_counter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('simple_domain_counter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('binding_vow_counter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('barrier_tech_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['barrier_tech_id'], ['barriertech.id'], name='barrierdetail_barrier_tech_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name='barrierdetail_match_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='barrierdetail_pkey')
    )
    op.drop_table('barrierrecord')
    # ### end Alembic commands ###
