"""adding regex to username field2.21 index added

Revision ID: b714a80bd3fa
Revises: 9cdfa4264b2d
Create Date: 2024-10-08 09:55:12.626929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b714a80bd3fa'
down_revision: Union[str, None] = '9cdfa4264b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    # ### end Alembic commands ###
