"""lastest revision

Revision ID: 1bbfa81b55c7
Revises: 1efae3e738c7
Create Date: 2024-12-22 20:03:16.507795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bbfa81b55c7'
down_revision: Union[str, None] = '1efae3e738c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'point',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('vote', 'has_been_added',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'has_been_added',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('vote', 'point',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
