"""added on_delete/cascade to user,player,admin

Revision ID: fa281adbd7dd
Revises: 935683e37a47
Create Date: 2024-09-25 13:12:53.745270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa281adbd7dd'
down_revision: Union[str, None] = '935683e37a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adminuser_user_id_fkey', 'adminuser', type_='foreignkey')
    op.create_foreign_key(None, 'adminuser', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('player_user_id_fkey', 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key('player_user_id_fkey', 'player', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'adminuser', type_='foreignkey')
    op.create_foreign_key('adminuser_user_id_fkey', 'adminuser', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
