"""uptest

Revision ID: 35392c97e431
Revises: 81895ee03375
Create Date: 2024-10-02 16:08:55.385587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35392c97e431'
down_revision: Union[str, None] = '81895ee03375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vote', 'ct_app_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vote', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vote', 'ct_app_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vote', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
