"""changed points from decimal to floats

Revision ID: 462a24d48590
Revises: 620f78bf7554
Create Date: 2024-10-14 21:43:19.655163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '462a24d48590'
down_revision: Union[str, None] = '620f78bf7554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'points',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'points',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
