"""modified vote table to inherit base vote

Revision ID: 81895ee03375
Revises: 0e4cbf9d5fb8
Create Date: 2024-09-26 22:12:47.091682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81895ee03375'
down_revision: Union[str, None] = '0e4cbf9d5fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('domain_expansion', sa.Boolean(), nullable=False))
    op.add_column('vote', sa.Column('binding_vow', sa.Boolean(), nullable=False))
    op.add_column('vote', sa.Column('simple_domain', sa.Boolean(), nullable=False))
    op.add_column('vote', sa.Column('de_time', sa.Time(), nullable=True))
    op.add_column('vote', sa.Column('bv_time', sa.Time(), nullable=True))
    op.add_column('vote', sa.Column('sd_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'sd_time')
    op.drop_column('vote', 'bv_time')
    op.drop_column('vote', 'de_time')
    op.drop_column('vote', 'simple_domain')
    op.drop_column('vote', 'binding_vow')
    op.drop_column('vote', 'domain_expansion')
    # ### end Alembic commands ###
