"""added indexing to all relavant table fields

Revision ID: 2523b492eaba
Revises: 452433266eb2
Create Date: 2024-10-14 23:08:30.032892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2523b492eaba'
down_revision: Union[str, None] = '452433266eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_adminpermissionlink_admin_id'), 'adminpermissionlink', ['admin_id'], unique=False)
    op.create_index(op.f('ix_adminpermissionlink_permission_id'), 'adminpermissionlink', ['permission_id'], unique=False)
    op.create_index(op.f('ix_adminuser_user_id'), 'adminuser', ['user_id'], unique=False)
    op.create_index(op.f('ix_ctapp_ct_id'), 'ctapp', ['ct_id'], unique=False)
    op.create_index(op.f('ix_permission_model'), 'permission', ['model'], unique=False)
    op.create_index(op.f('ix_player_age'), 'player', ['age'], unique=False)
    op.create_index(op.f('ix_player_barrier_tech_id'), 'player', ['barrier_tech_id'], unique=False)
    op.create_index(op.f('ix_player_colony_id'), 'player', ['colony_id'], unique=False)
    op.create_index(op.f('ix_player_created'), 'player', ['created'], unique=False)
    op.create_index(op.f('ix_player_ct_id'), 'player', ['ct_id'], unique=False)
    op.create_index(op.f('ix_player_gender'), 'player', ['gender'], unique=False)
    op.create_index(op.f('ix_player_grade'), 'player', ['grade'], unique=False)
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    op.create_index(op.f('ix_player_role'), 'player', ['role'], unique=False)
    op.create_index(op.f('ix_player_user_id'), 'player', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_country'), 'user', ['country'], unique=False)
    op.create_index(op.f('ix_vote_ct_app_id'), 'vote', ['ct_app_id'], unique=False)
    op.create_index(op.f('ix_vote_player_id'), 'vote', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_player_id'), table_name='vote')
    op.drop_index(op.f('ix_vote_ct_app_id'), table_name='vote')
    op.drop_index(op.f('ix_user_country'), table_name='user')
    op.drop_index(op.f('ix_player_user_id'), table_name='player')
    op.drop_index(op.f('ix_player_role'), table_name='player')
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_index(op.f('ix_player_grade'), table_name='player')
    op.drop_index(op.f('ix_player_gender'), table_name='player')
    op.drop_index(op.f('ix_player_ct_id'), table_name='player')
    op.drop_index(op.f('ix_player_created'), table_name='player')
    op.drop_index(op.f('ix_player_colony_id'), table_name='player')
    op.drop_index(op.f('ix_player_barrier_tech_id'), table_name='player')
    op.drop_index(op.f('ix_player_age'), table_name='player')
    op.drop_index(op.f('ix_permission_model'), table_name='permission')
    op.drop_index(op.f('ix_ctapp_ct_id'), table_name='ctapp')
    op.drop_index(op.f('ix_adminuser_user_id'), table_name='adminuser')
    op.drop_index(op.f('ix_adminpermissionlink_permission_id'), table_name='adminpermissionlink')
    op.drop_index(op.f('ix_adminpermissionlink_admin_id'), table_name='adminpermissionlink')
    # ### end Alembic commands ###
