"""adding point, has been added to vote table

Revision ID: 1efae3e738c7
Revises: 35f7f7311190
Create Date: 2024-10-28 00:09:54.546341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1efae3e738c7'
down_revision: Union[str, None] = '35f7f7311190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('point', sa.Float(), nullable=True))
    op.add_column('vote', sa.Column('has_been_added', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'has_been_added')
    op.drop_column('vote', 'point')
    # ### end Alembic commands ###
