"""added min and max length to player infos, also added name to ctapp

Revision ID: 4f8e2a9c53e4
Revises: 64a2fbec0518
Create Date: 2025-02-20 21:29:06.901647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f8e2a9c53e4'
down_revision: Union[str, None] = '64a2fbec0518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ctapp', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.drop_index('ix_player_role', table_name='player')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_player_role', 'player', ['role'], unique=False)
    op.drop_column('ctapp', 'name')
    # ### end Alembic commands ###
