"""made editing ct app name and app optional

Revision ID: 8d3e3bbdcd0d
Revises: 92c27518ef6f
Create Date: 2025-02-22 16:26:29.533655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d3e3bbdcd0d'
down_revision: Union[str, None] = '92c27518ef6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
