import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./fonts";
import { ThemeProvider } from "@/components/theme-povider";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "The Culling Games",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
            <Header />
            <main className="pt-[60px] h-dvh w-dvw">
              {children}
            </main>
          </ThemeProvider>
      </body>
    </html>
  );
}

