"""adding regex to username field

Revision ID: 0488f2cacd47
Revises: 4fa58bf352fd
Create Date: 2024-10-08 08:17:04.747851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0488f2cacd47'
down_revision: Union[str, None] = '4fa58bf352fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_match_colony_id'), 'match', ['colony_id'], unique=False)
    op.create_index(op.f('ix_match_winner_id'), 'match', ['winner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_winner_id'), table_name='match')
    op.drop_index(op.f('ix_match_colony_id'), table_name='match')
    # ### end Alembic commands ###
