"""corrected foreign key defaults in admins

Revision ID: 92495276cfea
Revises: f4ebd95ff412
Create Date: 2024-09-15 18:42:52.664726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92495276cfea'
down_revision: Union[str, None] = 'f4ebd95ff412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adminuser', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'colony_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('superuser', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('superuser', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('match', 'colony_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('adminuser', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
