"""test migration

Revision ID: f42629e80764
Revises: 2163003e63cc
Create Date: 2024-09-13 17:14:30.563061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f42629e80764'
down_revision: Union[str, None] = '2163003e63cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('t', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 't')
    # ### end Alembic commands ###
