"""removed super user from a table, and changed it into a bool on admin user

Revision ID: c645d44b9f92
Revises: 3f9d9b2569f9
Create Date: 2024-09-19 10:10:25.543653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c645d44b9f92'
down_revision: Union[str, None] = '3f9d9b2569f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('superuser')
    op.add_column('adminuser', sa.Column('is_superuser', sa.Boolean(), nullable=False, default=False))
    op.create_index(op.f('ix_permission_level'), 'permission', ['level'], unique=False)
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.drop_index(op.f('ix_permission_level'), table_name='permission')
    op.drop_column('adminuser', 'is_superuser')
    op.create_table('superuser',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='superuser_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='superuser_pkey')
    )
    # ### end Alembic commands ###
