export const COUNTRIES = [
  { id: "AF", description: "Afghanistan" },
  { id: "AL", description: "Albania" },
  { id: "DZ", description: "Algeria" },
  { id: "AD", description: "Andorra" },
  { id: "AO", description: "Angola" },
  { id: "AG", description: "Antigua and Barbuda" },
  { id: "AR", description: "Argentina" },
  { id: "AM", description: "Armenia" },
  { id: "AU", description: "Australia" },
  { id: "AT", description: "Austria" },
  { id: "AZ", description: "Azerbaijan" },
  { id: "BS", description: "Bahamas" },
  { id: "BH", description: "Bahrain" },
  { id: "BD", description: "Bangladesh" },
  { id: "BB", description: "Barbados" },
  { id: "BY", description: "Belarus" },
  { id: "BE", description: "Belgium" },
  { id: "BZ", description: "Belize" },
  { id: "BJ", description: "Benin" },
  { id: "BT", description: "Bhutan" },
  { id: "BO", description: "Bolivia" },
  { id: "BA", description: "Bosnia and Herzegovina" },
  { id: "BW", description: "Botswana" },
  { id: "BR", description: "Brazil" },
  { id: "BN", description: "Brunei" },
  { id: "BG", description: "Bulgaria" },
  { id: "BF", description: "Burkina Faso" },
  { id: "BI", description: "Burundi" },
  { id: "KH", description: "Cambodia" },
  { id: "CM", description: "Cameroon" },
  { id: "CA", description: "Canada" },
  { id: "CV", description: "Cape Verde" },
  { id: "CF", description: "Central African Republic" },
  { id: "TD", description: "Chad" },
  { id: "CL", description: "Chile" },
  { id: "CN", description: "China" },
  { id: "CO", description: "Colombia" },
  { id: "KM", description: "Comoros" },
  { id: "CG", description: "Congo (Brazzaville)" },
  { id: "CD", description: "Congo (Kinshasa)" },
  { id: "CR", description: "Costa Rica" },
  { id: "CI", description: "Côte d'Ivoire" },
  { id: "HR", description: "Croatia" },
  { id: "CU", description: "Cuba" },
  { id: "CY", description: "Cyprus" },
  { id: "CZ", description: "Czech Republic" },
  { id: "DK", description: "Denmark" },
  { id: "DJ", description: "Djibouti" },
  { id: "DM", description: "Dominica" },
  { id: "DO", description: "Dominican Republic" },
  { id: "EC", description: "Ecuador" },
  { id: "EG", description: "Egypt" },
  { id: "SV", description: "El Salvador" },
  { id: "GQ", description: "Equatorial Guinea" },
  { id: "ER", description: "Eritrea" },
  { id: "EE", description: "Estonia" },
  { id: "ET", description: "Ethiopia" },
  { id: "FJ", description: "Fiji" },
  { id: "FI", description: "Finland" },
  { id: "FR", description: "France" },
  { id: "GA", description: "Gabon" },
  { id: "GM", description: "Gambia" },
  { id: "GE", description: "Georgia" },
  { id: "DE", description: "Germany" },
  { id: "GH", description: "Ghana" },
  { id: "GR", description: "Greece" },
  { id: "GD", description: "Grenada" },
  { id: "GT", description: "Guatemala" },
  { id: "GN", description: "Guinea" },
  { id: "GW", description: "Guinea-Bissau" },
  { id: "GY", description: "Guyana" },
  { id: "HT", description: "Haiti" },
  { id: "HN", description: "Honduras" },
  { id: "HU", description: "Hungary" },
  { id: "IS", description: "Iceland" },
  { id: "IN", description: "India" },
  { id: "ID", description: "Indonesia" },
  { id: "IR", description: "Iran" },
  { id: "IQ", description: "Iraq" },
  { id: "IE", description: "Ireland" },
  { id: "IL", description: "Israel" },
  { id: "IT", description: "Italy" },
  { id: "JM", description: "Jamaica" },
  { id: "JP", description: "Japan" },
  { id: "JO", description: "Jordan" },
  { id: "KZ", description: "Kazakhstan" },
  { id: "KE", description: "Kenya" },
  { id: "KI", description: "Kiribati" },
  { id: "KW", description: "Kuwait" },
  { id: "KG", description: "Kyrgyzstan" },
  { id: "LA", description: "Laos" },
  { id: "LV", description: "Latvia" },
  { id: "LB", description: "Lebanon" },
  { id: "LS", description: "Lesotho" },
  { id: "LR", description: "Liberia" },
  { id: "LY", description: "Libya" },
  { id: "LI", description: "Liechtenstein" },
  { id: "LT", description: "Lithuania" },
  { id: "LU", description: "Luxembourg" },
  { id: "MG", description: "Madagascar" },
  { id: "MW", description: "Malawi" },
  { id: "MY", description: "Malaysia" },
  { id: "MV", description: "Maldives" },
  { id: "ML", description: "Mali" },
  { id: "MT", description: "Malta" },
  { id: "MX", description: "Mexico" },
  { id: "MD", description: "Moldova" },
  { id: "MC", description: "Monaco" },
  { id: "MN", description: "Mongolia" },
  { id: "ME", description: "Montenegro" },
  { id: "MA", description: "Morocco" },
  { id: "MZ", description: "Mozambique" },
  { id: "MM", description: "Myanmar" },
  { id: "NA", description: "Namibia" },
  { id: "NP", description: "Nepal" },
  { id: "NL", description: "Netherlands" },
  { id: "NZ", description: "New Zealand" },
  { id: "NI", description: "Nicaragua" },
  { id: "NE", description: "Niger" },
  { id: "NG", description: "Nigeria" },
  { id: "NO", description: "Norway" },
  { id: "PK", description: "Pakistan" },
  { id: "PA", description: "Panama" },
  { id: "PY", description: "Paraguay" },
  { id: "PE", description: "Peru" },
  { id: "PH", description: "Philippines" },
  { id: "PL", description: "Poland" },
  { id: "PT", description: "Portugal" },
  { id: "QA", description: "Qatar" },
  { id: "RO", description: "Romania" },
  { id: "RU", description: "Russia" },
  { id: "ZA", description: "South Africa" },
  { id: "ES", description: "Spain" },
  { id: "SE", description: "Sweden" },
  { id: "CH", description: "Switzerland" },
  { id: "TR", description: "Turkey" },
  { id: "US", description: "United States" },
  { id: "ZW", description: "Zimbabwe" },
];
